name: BattleShips
version: '${project.version}'
main: me.sk8ingduck.battleships.BattleShips
api-version: 1.16
authors: [ sk8ingDuck ]


commands:
  setspawn:
    description: Setspawn command
    usage: /<command>
    permission: battleships.admin