name: BattleShips
version: '${project.version}'
main: me.sk8ingduck.battleships.BattleShips
api-version: 1.16
authors: [ sk8ingDuck ]
depend: [ ChillsuchtAPI ]


commands:
  setspawn:
    description: Setspawn command
    usage: /<command>
    permission: battleships.admin
  stats:
    description: Stats command
    usage: /<command>
  start:
    description: Start command
    usage: /<command>
    permission: battleships.admin